version: '3'

services:
  pq_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: Efficent
      POSTGRES_USER: Mobile
      POSTGRES_PASSWORD: mobile
    ports:
      - "5432:5432"
    networks:
      - service_network

  service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pq_database
    networks:
      - service_network
    ports:
      - "8080:8080"
    environment:
      PORT: '8080'

  service2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pq_database
    networks:
      - service_network
    ports:
      - "8081:8081"
    environment:
      PORT: '8081'

  service3:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pq_database
    networks:
      - service_network
    ports:
      - "8082:8082"
    environment:
      PORT: '8082'

  nginx_reverse_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - service
      - service2
      - service3
    networks:
      - service_network
#    links:
#      - service


networks:
  service_network:
    driver: bridge
