global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:
  - job_name: 'service'
    static_configs:
      - targets: [ 'service:8080' ]
  - job_name: 'service2'
    static_configs:
      - targets: [ 'service2:8081' ]
  - job_name: 'service3'
    static_configs:
      - targets: [ 'service3:8082' ]
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]